### ISSUE TITLE
slider get stuck.when the bubble lifts up, for first it works fine. but seconf time it gets stuck

### ISSUE THREAD

**Issue by ghost** [rvamsikrishna/flutter_fluid_slider#6]

**Comment by rvamsikrishna** [comment]
Can you provide any images or a short video of the issue? It would also be good if you can provide any logs that show up.

**Comment by rvamsikrishna** [comment]
Closing the issue since there is no reply.

**Comment by ghost** [comment]
Sorry for late reply, I was busy with some work.i Dont see any issue in
logcat. But this is how it Looks

**Comment by ghost** [comment]
If you want to recreate the issue, just tap on the bubble for a while, and
it get stuck there!
